/**
 * Downloads the chosen artwork and records its provenance.
 *
 *   node scripts/fetch-art.mjs [<theme>]
 *
 * Reads `themes/<theme>/art-selection.json` — a map of card id to the index of
 * the chosen entry in `out/art-candidates.json` — then:
 *
 *   1. downloads each file into themes/<theme>/art/
 *   2. points theme.json's card at it
 *   3. regenerates ATTRIBUTION.md from Commons' own metadata
 *
 * Attribution is generated, never hand-written, so it cannot drift from what is
 * actually in the deck. The validator refuses to build if art is in use and
 * ATTRIBUTION.md is missing.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const UA = 'PathOfThePriest/0.1 (private print-and-play card project)';
const themeName = process.argv[2];
if (!themeName) {
  console.error('usage: node scripts/fetch-art.mjs <theme>');
  console.error('No theme ships with sourced art — dungeon-bright is drawn entirely in-repo.');
  process.exit(1);
}

const themeDir = path.join(ROOT, 'themes', themeName);
const artDir = path.join(themeDir, 'art');
const candidates = JSON.parse(fs.readFileSync(path.join(ROOT, 'out/art-candidates.json'), 'utf8'));
const selection = JSON.parse(fs.readFileSync(path.join(themeDir, 'art-selection.json'), 'utf8'));
const theme = JSON.parse(fs.readFileSync(path.join(themeDir, 'theme.json'), 'utf8'));

const slug = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);

/*
 * Fetch scaled thumbnails, not originals.
 *
 * Wikimedia returns 429 and explicitly asks callers to use the thumbnail sizes
 * rather than pulling full scans in bulk — reasonably, since the originals run
 * to 6456x8352 and several megabytes for an 816px-wide art window. 1280px
 * leaves plenty of room for cropping and keeps the repo small.
 */
const THUMB_WIDTH = 1280; // only certain widths are served; 1280 and 1920 are, 800 and 1024 are not

function thumbUrl(url, width) {
  const m = url.match(
    /^(https:\/\/upload\.wikimedia\.org\/wikipedia\/commons)\/([0-9a-f])\/([0-9a-f]{2})\/(.+)$/,
  );
  if (!m) return url;
  const [, base, a, b, name] = m;
  return `${base}/thumb/${a}/${b}/${name}/${width}px-${name}`;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function download(url, attempt = 0) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (res.status === 429 && attempt < 4) {
    await sleep([5000, 15000, 30000, 60000][attempt]);
    return download(url, attempt + 1);
  }
  if (!res.ok) {
    console.log(`    ${res.status} ${res.statusText}`);
    return null;
  }
  return Buffer.from(await res.arrayBuffer());
}

fs.mkdirSync(artDir, { recursive: true });

const used = [];

for (const [id, choice] of Object.entries(selection)) {
  const index = typeof choice === 'object' ? choice.index : choice;
  const pick = candidates[id]?.[index];
  if (!pick) {
    console.log(`  ${id}: no candidate at index ${index} — skipped`);
    continue;
  }

  const ext = path.extname(new URL(pick.url).pathname).toLowerCase();
  const file = `${id}-${slug(theme.cards[id]?.name ?? id)}${ext}`;
  const target = path.join(artDir, file);

  if (!fs.existsSync(target)) {
    const res = await download(thumbUrl(pick.url, THUMB_WIDTH));
    if (!res) {
      console.log(`  ${id}: download failed — skipped`);
      continue;
    }
    fs.writeFileSync(target, res);
    await sleep(1500);
  }

  theme.cards[id] = { ...theme.cards[id], art: file };
  if (typeof choice === 'object' && choice.focus) theme.cards[id].focus = choice.focus;

  used.push({ id, file, ...pick });
  console.log(`  ${id}  ${file}  (${(fs.statSync(target).size / 1024).toFixed(0)} KB)`);
}

fs.writeFileSync(path.join(themeDir, 'theme.json'), `${JSON.stringify(theme, null, 2)}\n`);

// --- attribution ------------------------------------------------------------

const rows = used
  .map((u) => {
    const name = theme.cards[u.id]?.name ?? u.id;
    const title = u.title.replace(/^File:/, '');
    return [
      `### ${u.id} — ${name}`,
      '',
      `- **File:** \`art/${u.file}\``,
      `- **Work:** ${title}`,
      u.artist ? `- **Creator:** ${u.artist}` : null,
      u.credit ? `- **Source:** ${u.credit}` : null,
      `- **Licence:** ${u.licence}`,
      u.descriptionUrl ? `- **Page:** ${u.descriptionUrl}` : null,
      '',
    ]
      .filter((l) => l !== null)
      .join('\n');
  })
  .join('\n');

fs.writeFileSync(
  path.join(themeDir, 'ATTRIBUTION.md'),
  `# Artwork attribution — ${theme.title}\n\n` +
    'Generated by `scripts/fetch-art.mjs` from Wikimedia Commons metadata. Do not\n' +
    'edit by hand: re-run the script instead, so this file cannot drift from the\n' +
    'images actually used in the deck.\n\n' +
    `All ${used.length} images are public domain or CC0 according to Commons.\n\n` +
    `${rows}\n`,
  'utf8',
);

console.log(`\n${used.length} images -> themes/${themeName}/art`);
console.log(`wrote themes/${themeName}/ATTRIBUTION.md`);
